package com.example.agrivault.ui.theme

import androidx.compose.ui.graphics.Color

// Light Theme Colors (Agricultural Greens & Earth Tones)
val md_light_primary = Color(0xFF2E7D32)
val md_light_onPrimary = Color(0xFFFFFFFF)
val md_light_primaryContainer = Color(0xFFB1F1AD)
val md_light_onPrimaryContainer = Color(0xFF002204)
val md_light_secondary = Color(0xFF53634F)
val md_light_onSecondary = Color(0xFFFFFFFF)
val md_light_secondaryContainer = Color(0xFFD6E8CE)
val md_light_onSecondaryContainer = Color(0xFF111F0F)
val md_light_tertiary = Color(0xFF386566)
val md_light_onTertiary = Color(0xFFFFFFFF)
val md_light_tertiaryContainer = Color(0xFFBCEBEB)
val md_light_onTertiaryContainer = Color(0xFF002021)
val md_light_error = Color(0xFFBA1A1A)
val md_light_errorContainer = Color(0xFFFFDAD6)
val md_light_onError = Color(0xFFFFFFFF)
val md_light_onErrorContainer = Color(0xFF410002)
val md_light_background = Color(0xFFFCFDF6)
val md_light_onBackground = Color(0xFF1A1C19)
val md_light_surface = Color(0xFFFCFDF6)
val md_light_onSurface = Color(0xFF1A1C19)
val md_light_surfaceVariant = Color(0xFFDEE5D8)
val md_light_onSurfaceVariant = Color(0xFF424940)
val md_light_outline = Color(0xFF72796F)

// Dark Theme Colors
val md_dark_primary = Color(0xFF96D593)
val md_dark_onPrimary = Color(0xFF00390A)
val md_dark_primaryContainer = Color(0xFF11521C)
val md_dark_onPrimaryContainer = Color(0xFFB1F1AD)
val md_dark_secondary = Color(0xFFBAD0B3)
val md_dark_onSecondary = Color(0xFF253423)
val md_dark_secondaryContainer = Color(0xFF3B4B38)
val md_dark_onSecondaryContainer = Color(0xFFD6E8CE)
val md_dark_tertiary = Color(0xFFA0CFCF)
val md_dark_onTertiary = Color(0xFF003738)
val md_dark_tertiaryContainer = Color(0xFF1E4D4E)
val md_dark_onTertiaryContainer = Color(0xFFBCEBEB)
val md_dark_error = Color(0xFFFFB4AB)
val md_dark_errorContainer = Color(0xFF93000A)
val md_dark_onError = Color(0xFF690005)
val md_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_dark_background = Color(0xFF1A1C19)
val md_dark_onBackground = Color(0xFFE2E3DD)
val md_dark_surface = Color(0xFF1A1C19)
val md_dark_onSurface = Color(0xFFE2E3DD)
val md_dark_surfaceVariant = Color(0xFF424940)
val md_dark_onSurfaceVariant = Color(0xFFC2C9BD)
val md_dark_outline = Color(0xFF8C9388)